'use strict';
export const routes_name = {
  SPLASH: 'SPLASH',
  LOGIN: 'LOGIN',
  REGIST: 'REGIST',
  LAYOUT: 'LAYOUT',
  HOME: 'HOME',
  PIGEON: 'PIGEON',
  PIGEON_ADD: 'PIGEON-ADD',
  PIGEON_SEARCH: 'PIGEON-SEARCH',
  PIGEON_DETAIL: 'PIGEON-DETAIL',
  PIGEON_ALL: 'PIGEON-ALL',
  PEDIGREE: 'PEDIGREE',
  ONELOFT: 'ONELOFT',
  ONELOFT_DETAIL: 'ONELOFT-DETAIL',
  FEATHER: 'FEATHER',
  FEATHER_ADD: 'FEATHER-ADD',
  FEATHER_SEARCH: 'FEATHER-SEARCH',
};
